# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文集名')),
            ],
            options={
                'verbose_name': '博客文集',
                'verbose_name_plural': '博客文集',
            },
        ),
    ]
